#! /bin/sh

sxhkd &
compton -r 12.0 -o 0.75 -l -15.0 -t -15.0 -I 0.028 -O 0.03 -D 3 -c -f -C -F -G &

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap           9

bspc config focused_border_color "#05fcc6"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 18

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a KDialog state=floating
bspc rule -a KMix state=floating

wmname LG3D
